package swp391.fa25.lms.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import swp391.fa25.lms.dto.blog.BlogCategoryDTO;
import swp391.fa25.lms.dto.blog.CreateBlogCategoryDTO;
import swp391.fa25.lms.dto.blog.UpdateBlogCategoryDTO;
import swp391.fa25.lms.model.BlogCategory;
import swp391.fa25.lms.repository.BlogCategoryRepository;
import swp391.fa25.lms.repository.BlogRepository;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class BlogCategoryServiceImpl implements BlogCategoryService {

    private final BlogCategoryRepository categoryRepository;
    private final BlogRepository blogRepository;

    @Override
    @Transactional
    public BlogCategoryDTO createCategory(CreateBlogCategoryDTO dto) {
        log.info("Creating blog category: {}", dto.getCategoryName());

        // Check if category name already exists
        if (categoryRepository.existsByCategoryNameIgnoreCase(dto.getCategoryName())) {
            throw new RuntimeException("Category name already exists: " + dto.getCategoryName());
        }

        BlogCategory category = new BlogCategory();
        category.setCategoryName(dto.getCategoryName());
        category.setDescription(dto.getDescription());
        
        // Set slug if provided, otherwise will be auto-generated by @PrePersist
        if (dto.getSlug() != null && !dto.getSlug().trim().isEmpty()) {
            category.setSlug(dto.getSlug());
        }

        // Set displayOrder: if not provided, use max + 1
        if (dto.getDisplayOrder() != null) {
            category.setDisplayOrder(dto.getDisplayOrder());
        } else {
            Integer maxOrder = categoryRepository.findMaxDisplayOrder();
            category.setDisplayOrder(maxOrder != null ? maxOrder + 1 : 1);
        }

        // Set status: default to ACTIVE if not provided
        if (dto.getStatus() != null && !dto.getStatus().trim().isEmpty()) {
            try {
                category.setStatus(BlogCategory.Status.valueOf(dto.getStatus().toUpperCase()));
            } catch (IllegalArgumentException e) {
                throw new RuntimeException("Invalid status: " + dto.getStatus());
            }
        } else {
            category.setStatus(BlogCategory.Status.ACTIVE);
        }

        // Slug will be auto-generated by @PrePersist
        BlogCategory savedCategory = categoryRepository.save(category);
        log.info("Category created successfully with ID: {}", savedCategory.getCategoryId());

        return new BlogCategoryDTO(savedCategory);
    }

    @Override
    @Transactional
    public BlogCategoryDTO updateCategory(UpdateBlogCategoryDTO dto) {
        log.info("Updating category ID: {}", dto.getCategoryId());

        BlogCategory category = categoryRepository.findById(dto.getCategoryId())
                .orElseThrow(() -> new RuntimeException("Category not found"));

        // Check if new name already exists (excluding current category)
        if (!category.getCategoryName().equalsIgnoreCase(dto.getCategoryName())) {
            if (categoryRepository.existsByCategoryNameIgnoreCase(dto.getCategoryName())) {
                throw new RuntimeException("Category name already exists: " + dto.getCategoryName());
            }
        }

        // Update fields
        category.setCategoryName(dto.getCategoryName());
        category.setDescription(dto.getDescription());

        // Update slug: if provided use it, otherwise regenerate from new name
        if (dto.getSlug() != null && !dto.getSlug().trim().isEmpty()) {
            String newSlug = dto.getSlug().trim();
            // Chỉ check unique nếu slug thay đổi
            if (!newSlug.equals(category.getSlug())) {
                // Validate slug unique (loại trừ chính nó)
                Optional<BlogCategory> existingSlug = categoryRepository.findBySlug(newSlug);
                if (existingSlug.isPresent() && !existingSlug.get().getCategoryId().equals(category.getCategoryId())) {
                    throw new RuntimeException("Slug already exists: " + newSlug);
                }
                category.setSlug(newSlug);
            }
        } else {
            // Regenerate slug from new category name
            String newSlug = dto.getCategoryName().toLowerCase()
                    .replaceAll("[^a-z0-9\\s-]", "")
                    .replaceAll("\\s+", "-")
                    .replaceAll("-+", "-")
                    .trim();
            // Check unique cho auto-generated slug
            if (!newSlug.equals(category.getSlug())) {
                Optional<BlogCategory> existingSlug = categoryRepository.findBySlug(newSlug);
                if (existingSlug.isPresent() && !existingSlug.get().getCategoryId().equals(category.getCategoryId())) {
                    // Slug bị trùng, thêm số vào cuối
                    int counter = 1;
                    String uniqueSlug = newSlug;
                    while (categoryRepository.findBySlug(uniqueSlug).isPresent()) {
                        uniqueSlug = newSlug + "-" + counter;
                        counter++;
                    }
                    category.setSlug(uniqueSlug);
                } else {
                    category.setSlug(newSlug);
                }
            }
        }

        if (dto.getDisplayOrder() != null) {
            category.setDisplayOrder(dto.getDisplayOrder());
        }

        // Update status
        BlogCategory.Status newStatus = BlogCategory.Status.valueOf(dto.getStatus().toUpperCase());
        category.setStatus(newStatus);

        // @PreUpdate will handle updatedAt
        BlogCategory updatedCategory = categoryRepository.save(category);
        log.info("Category updated successfully: {}", updatedCategory.getCategoryId());

        return new BlogCategoryDTO(updatedCategory);
    }

    @Override
    @Transactional
    public void deleteCategory(Long categoryId) {
        log.info("Deleting category ID: {}", categoryId);

        BlogCategory category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new RuntimeException("Category not found"));

        // Check if category has any blogs
        long blogCount = blogRepository.countByCategory(category);
        if (blogCount > 0) {
            throw new RuntimeException("Cannot delete category with existing blogs. " +
                    "Please reassign or delete " + blogCount + " blog(s) first.");
        }

        categoryRepository.delete(category);
        log.info("Category deleted successfully: {}", categoryId);
    }

    @Override
    @Transactional(readOnly = true)
    public BlogCategoryDTO getCategoryById(Long categoryId) {
        BlogCategory category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new RuntimeException("Category not found"));

        // Get blog count
        long blogCount = blogRepository.countByCategory(category);
        return new BlogCategoryDTO(category, blogCount);
    }

    @Override
    @Transactional(readOnly = true)
    public BlogCategoryDTO getCategoryBySlug(String slug) {
        BlogCategory category = categoryRepository.findBySlug(slug)
                .orElseThrow(() -> new RuntimeException("Không tìm thấy category với slug: " + slug));

        // Get blog count
        long blogCount = blogRepository.countByCategory(category);
        return new BlogCategoryDTO(category, blogCount);
    }

    @Override
    @Transactional(readOnly = true)
    public List<BlogCategoryDTO> getAllCategories() {
        List<BlogCategory> categories = categoryRepository.findAllOrderByDisplayOrder();
        return categories.stream()
                .map(category -> {
                    long blogCount = blogRepository.countByCategory(category);
                    return new BlogCategoryDTO(category, blogCount);
                })
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<BlogCategoryDTO> searchCategories(String keyword, String status, String sortBy) {
        List<BlogCategory> categories;
        
        // Convert String status to enum if provided
        BlogCategory.Status statusEnum = null;
        if (status != null && !status.trim().isEmpty()) {
            try {
                statusEnum = BlogCategory.Status.valueOf(status.toUpperCase());
            } catch (IllegalArgumentException e) {
                log.warn("Invalid status value: {}", status);
            }
        }
        
        // Search categories
        categories = categoryRepository.search(keyword, statusEnum);
        
        // Sort categories based on sortBy parameter
        if (sortBy != null && !sortBy.trim().isEmpty()) {
            switch (sortBy.toLowerCase()) {
                case "categoryname":
                    categories.sort((a, b) -> {
                        if (a.getCategoryName() == null && b.getCategoryName() == null) return 0;
                        if (a.getCategoryName() == null) return 1;
                        if (b.getCategoryName() == null) return -1;
                        return a.getCategoryName().compareToIgnoreCase(b.getCategoryName());
                    });
                    break;
                case "displayorder":
                    categories.sort((a, b) -> {
                        Integer orderA = a.getDisplayOrder() != null ? a.getDisplayOrder() : 0;
                        Integer orderB = b.getDisplayOrder() != null ? b.getDisplayOrder() : 0;
                        int compare = orderA.compareTo(orderB);
                        if (compare == 0) {
                            // Secondary sort by category name
                            String nameA = a.getCategoryName() != null ? a.getCategoryName() : "";
                            String nameB = b.getCategoryName() != null ? b.getCategoryName() : "";
                            return nameA.compareToIgnoreCase(nameB);
                        }
                        return compare;
                    });
                    break;
                case "createdat":
                    categories.sort((a, b) -> {
                        if (a.getCreatedAt() == null && b.getCreatedAt() == null) return 0;
                        if (a.getCreatedAt() == null) return 1;
                        if (b.getCreatedAt() == null) return -1;
                        return b.getCreatedAt().compareTo(a.getCreatedAt()); // DESC
                    });
                    break;
                case "status":
                    categories.sort((a, b) -> {
                        if (a.getStatus() == null && b.getStatus() == null) return 0;
                        if (a.getStatus() == null) return 1;
                        if (b.getStatus() == null) return -1;
                        return a.getStatus().name().compareTo(b.getStatus().name());
                    });
                    break;
                default:
                    // Default: sort by displayOrder
                    categories.sort((a, b) -> {
                        Integer orderA = a.getDisplayOrder() != null ? a.getDisplayOrder() : 0;
                        Integer orderB = b.getDisplayOrder() != null ? b.getDisplayOrder() : 0;
                        int compare = orderA.compareTo(orderB);
                        if (compare == 0) {
                            String nameA = a.getCategoryName() != null ? a.getCategoryName() : "";
                            String nameB = b.getCategoryName() != null ? b.getCategoryName() : "";
                            return nameA.compareToIgnoreCase(nameB);
                        }
                        return compare;
                    });
                    break;
            }
        } else {
            // Default: sort by displayOrder
            categories.sort((a, b) -> {
                Integer orderA = a.getDisplayOrder() != null ? a.getDisplayOrder() : 0;
                Integer orderB = b.getDisplayOrder() != null ? b.getDisplayOrder() : 0;
                int compare = orderA.compareTo(orderB);
                if (compare == 0) {
                    String nameA = a.getCategoryName() != null ? a.getCategoryName() : "";
                    String nameB = b.getCategoryName() != null ? b.getCategoryName() : "";
                    return nameA.compareToIgnoreCase(nameB);
                }
                return compare;
            });
        }
        
        return categories.stream()
                .map(category -> {
                    long blogCount = blogRepository.countByCategory(category);
                    return new BlogCategoryDTO(category, blogCount);
                })
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<BlogCategoryDTO> getActiveCategories() {
        List<BlogCategory> categories = categoryRepository.findAllActiveOrderByDisplayOrder();
        return categories.stream()
                .map(category -> {
                    // Chỉ đếm bài viết PUBLISHED cho public view
                    long blogCount = blogRepository.countPublishedBlogsByCategory(category);
                    return new BlogCategoryDTO(category, blogCount);
                })
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public BlogCategoryDTO activateCategory(Long categoryId) {
        log.info("Activating category ID: {}", categoryId);

        BlogCategory category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new RuntimeException("Category not found"));

        category.setStatus(BlogCategory.Status.ACTIVE);
        BlogCategory savedCategory = categoryRepository.save(category);

        log.info("Category activated successfully: {}", categoryId);
        return new BlogCategoryDTO(savedCategory);
    }

    @Override
    @Transactional
    public BlogCategoryDTO deactivateCategory(Long categoryId) {
        log.info("Deactivating category ID: {}", categoryId);

        BlogCategory category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new RuntimeException("Category not found"));

        category.setStatus(BlogCategory.Status.INACTIVE);
        BlogCategory savedCategory = categoryRepository.save(category);

        log.info("Category deactivated successfully: {}", categoryId);
        return new BlogCategoryDTO(savedCategory);
    }
}
